{
 "title": "Azure OpenAI Reverse Proxy",
 "tags": [
  "azure-openai",
  "proxy"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "Remaining tokens",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "azure_openai_remaining_tokens",
     "legendFormat": "{{account_name}} - {{deployment_name}}"
    }
   ]
  },
  {
   "title": "Remaining requests",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 9, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "azure_openai_remaining_requests",
     "legendFormat": "{{account_name}} - {{deployment_name}}"
    }
   ]
  },
  {
   "title": "Failed requests (HTTP 429)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(azure_openai_failed_http_requests{status_code=\"429\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Remaining requests over time",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 22, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "azure_openai_remaining_requests",
     "legendFormat": "{{account_name}} - {{deployment_name}}"
    }
   ]
  },
  {
   "title": "Remaining tokens over time",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 22, "x": 0, "y": 16 },
   "targets": [
    { "expr": "azure_openai_remaining_tokens", "legendFormat": "__auto" }
   ]
  }
 ]
}